// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.irealizze.modelo.perene;

import com.nanuvem.irealizze.modelo.perene.Preco;
import com.nanuvem.irealizze.modelo.perene.PrecoDataOnDemand;
import com.nanuvem.irealizze.modelo.perene.PrecoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PrecoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PrecoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PrecoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PrecoIntegrationTest: @Transactional;
    
    @Autowired
    private PrecoDataOnDemand PrecoIntegrationTest.dod;
    
    @Test
    public void PrecoIntegrationTest.testCountPrecoes() {
        Assert.assertNotNull("Data on demand for 'Preco' failed to initialize correctly", dod.getRandomPreco());
        long count = Preco.countPrecoes();
        Assert.assertTrue("Counter for 'Preco' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PrecoIntegrationTest.testFindPreco() {
        Preco obj = dod.getRandomPreco();
        Assert.assertNotNull("Data on demand for 'Preco' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Preco' failed to provide an identifier", id);
        obj = Preco.findPreco(id);
        Assert.assertNotNull("Find method for 'Preco' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Preco' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PrecoIntegrationTest.testFindAllPrecoes() {
        Assert.assertNotNull("Data on demand for 'Preco' failed to initialize correctly", dod.getRandomPreco());
        long count = Preco.countPrecoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Preco', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Preco> result = Preco.findAllPrecoes();
        Assert.assertNotNull("Find all method for 'Preco' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Preco' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PrecoIntegrationTest.testFindPrecoEntries() {
        Assert.assertNotNull("Data on demand for 'Preco' failed to initialize correctly", dod.getRandomPreco());
        long count = Preco.countPrecoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Preco> result = Preco.findPrecoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Preco' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Preco' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PrecoIntegrationTest.testFlush() {
        Preco obj = dod.getRandomPreco();
        Assert.assertNotNull("Data on demand for 'Preco' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Preco' failed to provide an identifier", id);
        obj = Preco.findPreco(id);
        Assert.assertNotNull("Find method for 'Preco' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPreco(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Preco' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrecoIntegrationTest.testMergeUpdate() {
        Preco obj = dod.getRandomPreco();
        Assert.assertNotNull("Data on demand for 'Preco' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Preco' failed to provide an identifier", id);
        obj = Preco.findPreco(id);
        boolean modified =  dod.modifyPreco(obj);
        Integer currentVersion = obj.getVersion();
        Preco merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Preco' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrecoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Preco' failed to initialize correctly", dod.getRandomPreco());
        Preco obj = dod.getNewTransientPreco(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Preco' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Preco' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Preco' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PrecoIntegrationTest.testRemove() {
        Preco obj = dod.getRandomPreco();
        Assert.assertNotNull("Data on demand for 'Preco' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Preco' failed to provide an identifier", id);
        obj = Preco.findPreco(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Preco' with identifier '" + id + "'", Preco.findPreco(id));
    }
    
}
