// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.irealizze.modelo.perene;

import com.nanuvem.irealizze.modelo.perene.Responsavel;
import com.nanuvem.irealizze.modelo.perene.ResponsavelDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ResponsavelDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ResponsavelDataOnDemand: @Component;
    
    private Random ResponsavelDataOnDemand.rnd = new SecureRandom();
    
    private List<Responsavel> ResponsavelDataOnDemand.data;
    
    public Responsavel ResponsavelDataOnDemand.getNewTransientResponsavel(int index) {
        Responsavel obj = new Responsavel();
        setLogin(obj, index);
        return obj;
    }
    
    public void ResponsavelDataOnDemand.setLogin(Responsavel obj, int index) {
        String login = "login_" + index;
        obj.setLogin(login);
    }
    
    public Responsavel ResponsavelDataOnDemand.getSpecificResponsavel(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Responsavel obj = data.get(index);
        Long id = obj.getId();
        return Responsavel.findResponsavel(id);
    }
    
    public Responsavel ResponsavelDataOnDemand.getRandomResponsavel() {
        init();
        Responsavel obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Responsavel.findResponsavel(id);
    }
    
    public boolean ResponsavelDataOnDemand.modifyResponsavel(Responsavel obj) {
        return false;
    }
    
    public void ResponsavelDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Responsavel.findResponsavelEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Responsavel' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Responsavel>();
        for (int i = 0; i < 10; i++) {
            Responsavel obj = getNewTransientResponsavel(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
