// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.irealizze.modelo.perene;

import com.nanuvem.irealizze.modelo.perene.TabelaPreco;
import com.nanuvem.irealizze.modelo.perene.TabelaPrecoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TabelaPrecoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TabelaPrecoDataOnDemand: @Component;
    
    private Random TabelaPrecoDataOnDemand.rnd = new SecureRandom();
    
    private List<TabelaPreco> TabelaPrecoDataOnDemand.data;
    
    public TabelaPreco TabelaPrecoDataOnDemand.getNewTransientTabelaPreco(int index) {
        TabelaPreco obj = new TabelaPreco();
        setFimVigencia(obj, index);
        setInicioVigencia(obj, index);
        setNome(obj, index);
        setVigente(obj, index);
        return obj;
    }
    
    public void TabelaPrecoDataOnDemand.setFimVigencia(TabelaPreco obj, int index) {
        Calendar fimVigencia = Calendar.getInstance();
        obj.setFimVigencia(fimVigencia);
    }
    
    public void TabelaPrecoDataOnDemand.setInicioVigencia(TabelaPreco obj, int index) {
        Calendar inicioVigencia = Calendar.getInstance();
        obj.setInicioVigencia(inicioVigencia);
    }
    
    public void TabelaPrecoDataOnDemand.setNome(TabelaPreco obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public void TabelaPrecoDataOnDemand.setVigente(TabelaPreco obj, int index) {
        Boolean vigente = Boolean.TRUE;
        obj.setVigente(vigente);
    }
    
    public TabelaPreco TabelaPrecoDataOnDemand.getSpecificTabelaPreco(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TabelaPreco obj = data.get(index);
        Long id = obj.getId();
        return TabelaPreco.findTabelaPreco(id);
    }
    
    public TabelaPreco TabelaPrecoDataOnDemand.getRandomTabelaPreco() {
        init();
        TabelaPreco obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TabelaPreco.findTabelaPreco(id);
    }
    
    public boolean TabelaPrecoDataOnDemand.modifyTabelaPreco(TabelaPreco obj) {
        return false;
    }
    
    public void TabelaPrecoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TabelaPreco.findTabelaPrecoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TabelaPreco' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TabelaPreco>();
        for (int i = 0; i < 10; i++) {
            TabelaPreco obj = getNewTransientTabelaPreco(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
