// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.irealizze.modelo.perene;

import com.nanuvem.irealizze.modelo.perene.TabelaPreco;
import com.nanuvem.irealizze.modelo.perene.TabelaPrecoDataOnDemand;
import com.nanuvem.irealizze.modelo.perene.TabelaPrecoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TabelaPrecoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TabelaPrecoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TabelaPrecoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TabelaPrecoIntegrationTest: @Transactional;
    
    @Autowired
    private TabelaPrecoDataOnDemand TabelaPrecoIntegrationTest.dod;
    
    @Test
    public void TabelaPrecoIntegrationTest.testCountTabelaPrecoes() {
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to initialize correctly", dod.getRandomTabelaPreco());
        long count = TabelaPreco.countTabelaPrecoes();
        Assert.assertTrue("Counter for 'TabelaPreco' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TabelaPrecoIntegrationTest.testFindTabelaPreco() {
        TabelaPreco obj = dod.getRandomTabelaPreco();
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to provide an identifier", id);
        obj = TabelaPreco.findTabelaPreco(id);
        Assert.assertNotNull("Find method for 'TabelaPreco' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TabelaPreco' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TabelaPrecoIntegrationTest.testFindAllTabelaPrecoes() {
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to initialize correctly", dod.getRandomTabelaPreco());
        long count = TabelaPreco.countTabelaPrecoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'TabelaPreco', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TabelaPreco> result = TabelaPreco.findAllTabelaPrecoes();
        Assert.assertNotNull("Find all method for 'TabelaPreco' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TabelaPreco' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TabelaPrecoIntegrationTest.testFindTabelaPrecoEntries() {
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to initialize correctly", dod.getRandomTabelaPreco());
        long count = TabelaPreco.countTabelaPrecoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TabelaPreco> result = TabelaPreco.findTabelaPrecoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TabelaPreco' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TabelaPreco' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TabelaPrecoIntegrationTest.testFlush() {
        TabelaPreco obj = dod.getRandomTabelaPreco();
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to provide an identifier", id);
        obj = TabelaPreco.findTabelaPreco(id);
        Assert.assertNotNull("Find method for 'TabelaPreco' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTabelaPreco(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TabelaPreco' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TabelaPrecoIntegrationTest.testMergeUpdate() {
        TabelaPreco obj = dod.getRandomTabelaPreco();
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to provide an identifier", id);
        obj = TabelaPreco.findTabelaPreco(id);
        boolean modified =  dod.modifyTabelaPreco(obj);
        Integer currentVersion = obj.getVersion();
        TabelaPreco merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TabelaPreco' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TabelaPrecoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to initialize correctly", dod.getRandomTabelaPreco());
        TabelaPreco obj = dod.getNewTransientTabelaPreco(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TabelaPreco' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TabelaPreco' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TabelaPrecoIntegrationTest.testRemove() {
        TabelaPreco obj = dod.getRandomTabelaPreco();
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TabelaPreco' failed to provide an identifier", id);
        obj = TabelaPreco.findTabelaPreco(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TabelaPreco' with identifier '" + id + "'", TabelaPreco.findTabelaPreco(id));
    }
    
}
