// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.irealizze.modelo.perene;

import com.nanuvem.irealizze.modelo.perene.TipoItem;
import com.nanuvem.irealizze.modelo.perene.TipoItemDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TipoItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TipoItemDataOnDemand: @Component;
    
    private Random TipoItemDataOnDemand.rnd = new SecureRandom();
    
    private List<TipoItem> TipoItemDataOnDemand.data;
    
    public TipoItem TipoItemDataOnDemand.getNewTransientTipoItem(int index) {
        TipoItem obj = new TipoItem();
        setNome(obj, index);
        setPai(obj, index);
        return obj;
    }
    
    public void TipoItemDataOnDemand.setNome(TipoItem obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public void TipoItemDataOnDemand.setPai(TipoItem obj, int index) {
        TipoItem pai = obj;
        obj.setPai(pai);
    }
    
    public TipoItem TipoItemDataOnDemand.getSpecificTipoItem(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TipoItem obj = data.get(index);
        Long id = obj.getId();
        return TipoItem.findTipoItem(id);
    }
    
    public TipoItem TipoItemDataOnDemand.getRandomTipoItem() {
        init();
        TipoItem obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TipoItem.findTipoItem(id);
    }
    
    public boolean TipoItemDataOnDemand.modifyTipoItem(TipoItem obj) {
        return false;
    }
    
    public void TipoItemDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TipoItem.findTipoItemEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TipoItem' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TipoItem>();
        for (int i = 0; i < 10; i++) {
            TipoItem obj = getNewTransientTipoItem(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
