// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.irealizze.modelo.perene;

import com.nanuvem.irealizze.modelo.perene.TipoItem;
import com.nanuvem.irealizze.modelo.perene.TipoItemDataOnDemand;
import com.nanuvem.irealizze.modelo.perene.TipoItemIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TipoItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TipoItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TipoItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TipoItemIntegrationTest: @Transactional;
    
    @Autowired
    TipoItemDataOnDemand TipoItemIntegrationTest.dod;
    
    @Test
    public void TipoItemIntegrationTest.testCountTipoItems() {
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to initialize correctly", dod.getRandomTipoItem());
        long count = TipoItem.countTipoItems();
        Assert.assertTrue("Counter for 'TipoItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TipoItemIntegrationTest.testFindTipoItem() {
        TipoItem obj = dod.getRandomTipoItem();
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to provide an identifier", id);
        obj = TipoItem.findTipoItem(id);
        Assert.assertNotNull("Find method for 'TipoItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TipoItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TipoItemIntegrationTest.testFindAllTipoItems() {
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to initialize correctly", dod.getRandomTipoItem());
        long count = TipoItem.countTipoItems();
        Assert.assertTrue("Too expensive to perform a find all test for 'TipoItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TipoItem> result = TipoItem.findAllTipoItems();
        Assert.assertNotNull("Find all method for 'TipoItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TipoItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TipoItemIntegrationTest.testFindTipoItemEntries() {
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to initialize correctly", dod.getRandomTipoItem());
        long count = TipoItem.countTipoItems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TipoItem> result = TipoItem.findTipoItemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TipoItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TipoItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TipoItemIntegrationTest.testFlush() {
        TipoItem obj = dod.getRandomTipoItem();
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to provide an identifier", id);
        obj = TipoItem.findTipoItem(id);
        Assert.assertNotNull("Find method for 'TipoItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTipoItem(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TipoItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TipoItemIntegrationTest.testMergeUpdate() {
        TipoItem obj = dod.getRandomTipoItem();
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to provide an identifier", id);
        obj = TipoItem.findTipoItem(id);
        boolean modified =  dod.modifyTipoItem(obj);
        Integer currentVersion = obj.getVersion();
        TipoItem merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TipoItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TipoItemIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to initialize correctly", dod.getRandomTipoItem());
        TipoItem obj = dod.getNewTransientTipoItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TipoItem' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TipoItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TipoItemIntegrationTest.testRemove() {
        TipoItem obj = dod.getRandomTipoItem();
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoItem' failed to provide an identifier", id);
        obj = TipoItem.findTipoItem(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TipoItem' with identifier '" + id + "'", TipoItem.findTipoItem(id));
    }
    
}
