// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.irealizze.modelo;

import com.nanuvem.irealizze.modelo.Alocacao;
import com.nanuvem.irealizze.modelo.AlocacaoDataOnDemand;
import com.nanuvem.irealizze.modelo.Elemento;
import com.nanuvem.irealizze.modelo.ElementoDataOnDemand;
import com.nanuvem.irealizze.modelo.Periodo;
import com.nanuvem.irealizze.modelo.PeriodoDataOnDemand;
import com.nanuvem.irealizze.modelo.perene.ResponsavelDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AlocacaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AlocacaoDataOnDemand: @Component;
    
    private Random AlocacaoDataOnDemand.rnd = new SecureRandom();
    
    private List<Alocacao> AlocacaoDataOnDemand.data;
    
    @Autowired
    private ElementoDataOnDemand AlocacaoDataOnDemand.elementoDataOnDemand;
    
    @Autowired
    private PeriodoDataOnDemand AlocacaoDataOnDemand.periodoDataOnDemand;
    
    @Autowired
    private ResponsavelDataOnDemand AlocacaoDataOnDemand.responsavelDataOnDemand;
    
    public Alocacao AlocacaoDataOnDemand.getNewTransientAlocacao(int index) {
        Alocacao obj = new Alocacao();
        setElemento(obj, index);
        setPeriodo(obj, index);
        setPrioridade(obj, index);
        return obj;
    }
    
    public void AlocacaoDataOnDemand.setElemento(Alocacao obj, int index) {
        Elemento elemento = elementoDataOnDemand.getRandomElemento();
        obj.setElemento(elemento);
    }
    
    public void AlocacaoDataOnDemand.setPeriodo(Alocacao obj, int index) {
        Periodo periodo = periodoDataOnDemand.getRandomPeriodo();
        obj.setPeriodo(periodo);
    }
    
    public void AlocacaoDataOnDemand.setPrioridade(Alocacao obj, int index) {
        int prioridade = index;
        obj.setPrioridade(prioridade);
    }
    
    public Alocacao AlocacaoDataOnDemand.getSpecificAlocacao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Alocacao obj = data.get(index);
        Long id = obj.getId();
        return Alocacao.findAlocacao(id);
    }
    
    public Alocacao AlocacaoDataOnDemand.getRandomAlocacao() {
        init();
        Alocacao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Alocacao.findAlocacao(id);
    }
    
    public boolean AlocacaoDataOnDemand.modifyAlocacao(Alocacao obj) {
        return false;
    }
    
    public void AlocacaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Alocacao.findAlocacaoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Alocacao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Alocacao>();
        for (int i = 0; i < 10; i++) {
            Alocacao obj = getNewTransientAlocacao(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
