// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.irealizze.modelo;

import com.nanuvem.irealizze.modelo.ElementoFolha;
import com.nanuvem.irealizze.modelo.ElementoFolhaDataOnDemand;
import com.nanuvem.irealizze.modelo.ElementoFolhaIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ElementoFolhaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ElementoFolhaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ElementoFolhaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ElementoFolhaIntegrationTest: @Transactional;
    
    @Autowired
    private ElementoFolhaDataOnDemand ElementoFolhaIntegrationTest.dod;
    
    @Test
    public void ElementoFolhaIntegrationTest.testCountElementoFolhas() {
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to initialize correctly", dod.getRandomElementoFolha());
        long count = ElementoFolha.countElementoFolhas();
        Assert.assertTrue("Counter for 'ElementoFolha' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ElementoFolhaIntegrationTest.testFindElementoFolha() {
        ElementoFolha obj = dod.getRandomElementoFolha();
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to provide an identifier", id);
        obj = ElementoFolha.findElementoFolha(id);
        Assert.assertNotNull("Find method for 'ElementoFolha' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ElementoFolha' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ElementoFolhaIntegrationTest.testFindAllElementoFolhas() {
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to initialize correctly", dod.getRandomElementoFolha());
        long count = ElementoFolha.countElementoFolhas();
        Assert.assertTrue("Too expensive to perform a find all test for 'ElementoFolha', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ElementoFolha> result = ElementoFolha.findAllElementoFolhas();
        Assert.assertNotNull("Find all method for 'ElementoFolha' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ElementoFolha' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ElementoFolhaIntegrationTest.testFindElementoFolhaEntries() {
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to initialize correctly", dod.getRandomElementoFolha());
        long count = ElementoFolha.countElementoFolhas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ElementoFolha> result = ElementoFolha.findElementoFolhaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ElementoFolha' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ElementoFolha' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ElementoFolhaIntegrationTest.testFlush() {
        ElementoFolha obj = dod.getRandomElementoFolha();
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to provide an identifier", id);
        obj = ElementoFolha.findElementoFolha(id);
        Assert.assertNotNull("Find method for 'ElementoFolha' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyElementoFolha(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ElementoFolha' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ElementoFolhaIntegrationTest.testMergeUpdate() {
        ElementoFolha obj = dod.getRandomElementoFolha();
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to provide an identifier", id);
        obj = ElementoFolha.findElementoFolha(id);
        boolean modified =  dod.modifyElementoFolha(obj);
        Integer currentVersion = obj.getVersion();
        ElementoFolha merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ElementoFolha' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ElementoFolhaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to initialize correctly", dod.getRandomElementoFolha());
        ElementoFolha obj = dod.getNewTransientElementoFolha(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ElementoFolha' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ElementoFolha' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ElementoFolhaIntegrationTest.testRemove() {
        ElementoFolha obj = dod.getRandomElementoFolha();
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ElementoFolha' failed to provide an identifier", id);
        obj = ElementoFolha.findElementoFolha(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ElementoFolha' with identifier '" + id + "'", ElementoFolha.findElementoFolha(id));
    }
    
}
