// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.irealizze.modelo;

import com.nanuvem.irealizze.modelo.Elemento;
import com.nanuvem.irealizze.modelo.ElementoDataOnDemand;
import com.nanuvem.irealizze.modelo.ElementoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ElementoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ElementoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ElementoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ElementoIntegrationTest: @Transactional;
    
    @Autowired
    private ElementoDataOnDemand ElementoIntegrationTest.dod;
    
    @Test
    public void ElementoIntegrationTest.testCountElementoes() {
        Assert.assertNotNull("Data on demand for 'Elemento' failed to initialize correctly", dod.getRandomElemento());
        long count = Elemento.countElementoes();
        Assert.assertTrue("Counter for 'Elemento' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ElementoIntegrationTest.testFindElemento() {
        Elemento obj = dod.getRandomElemento();
        Assert.assertNotNull("Data on demand for 'Elemento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Elemento' failed to provide an identifier", id);
        obj = Elemento.findElemento(id);
        Assert.assertNotNull("Find method for 'Elemento' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Elemento' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ElementoIntegrationTest.testFindAllElementoes() {
        Assert.assertNotNull("Data on demand for 'Elemento' failed to initialize correctly", dod.getRandomElemento());
        long count = Elemento.countElementoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Elemento', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Elemento> result = Elemento.findAllElementoes();
        Assert.assertNotNull("Find all method for 'Elemento' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Elemento' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ElementoIntegrationTest.testFindElementoEntries() {
        Assert.assertNotNull("Data on demand for 'Elemento' failed to initialize correctly", dod.getRandomElemento());
        long count = Elemento.countElementoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Elemento> result = Elemento.findElementoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Elemento' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Elemento' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ElementoIntegrationTest.testFlush() {
        Elemento obj = dod.getRandomElemento();
        Assert.assertNotNull("Data on demand for 'Elemento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Elemento' failed to provide an identifier", id);
        obj = Elemento.findElemento(id);
        Assert.assertNotNull("Find method for 'Elemento' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyElemento(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Elemento' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ElementoIntegrationTest.testMergeUpdate() {
        Elemento obj = dod.getRandomElemento();
        Assert.assertNotNull("Data on demand for 'Elemento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Elemento' failed to provide an identifier", id);
        obj = Elemento.findElemento(id);
        boolean modified =  dod.modifyElemento(obj);
        Integer currentVersion = obj.getVersion();
        Elemento merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Elemento' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ElementoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Elemento' failed to initialize correctly", dod.getRandomElemento());
        Elemento obj = dod.getNewTransientElemento(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Elemento' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Elemento' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Elemento' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ElementoIntegrationTest.testRemove() {
        Elemento obj = dod.getRandomElemento();
        Assert.assertNotNull("Data on demand for 'Elemento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Elemento' failed to provide an identifier", id);
        obj = Elemento.findElemento(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Elemento' with identifier '" + id + "'", Elemento.findElemento(id));
    }
    
}
